app_meal:
    resource: "@AppBundle/Controller/MealController.php"
    type:     annotation

app_category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

app_recipe:
    resource: "@AppBundle/Controller/RecipeController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FosUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group


